let hiddenElements,width=document.body.clientWidth;function createObserver(){let a=new IntersectionObserver(a=>{a.forEach(a=>{a.isIntersecting&&width>=991&&(a.target.classList.add("show"),a.target.classList.remove("hidden"))})},{root:null,rootMargin:"0px",threshold:0});hiddenElements.forEach(e=>a.observe(e))}window.addEventListener("resize",()=>width=window.innerWidth),window.addEventListener("load",a=>{hiddenElements=document.querySelectorAll(".hidden"),createObserver()});let AVATARS={femaleLight:{src:"images/avatar-female-light.png",alt:"avatar graphic female light"},maleDark:{src:"images/avatar-male-dark.png",alt:"avatar graphic male dark"}};document.addEventListener("DOMContentLoaded",function(){let a=[{avatar:AVATARS.maleDark,name:"Nino Blac",company:{name:"Life180 Coaching",href:null},text:"Collaborating with Mario was a fantastic experience. He is concise, thorough, and possesses a keen eye for detail. Mario excels at following instructions, consistently meeting deadlines. I highly recommend him to anyone in search of web design services. I look forward to the possibility of working with him again in the future."},{avatar:AVATARS.femaleLight,name:"Stephanie Mason-Teague",company:{name:"Ormond Memorial Art Museum & Gardens",href:"https://www.ormondartmuseum.org/"},text:"Mario did a wonderful job, on time, and exceeded our expectations. He was very professional to work with and delivered an exceptional product."}],e=document.querySelector("#testimonials-container"),t=a=>{let e=`
    <div class="testimonials-avatar">
      <img src="${a.avatar.src}" alt="${a.avatar.alt}">
    </div>
    <h3>${a.name}</h3>
    <div class="text-link">
      <a href="${a.company.href}" target="_blank" style="color: #fd5618; text-decoration: none;"><h4>${a.company.name}</h4></a>
    </div>
    <div class="testimonials-rating">
      <img src="images/star-fill.svg" alt="star rating graphic">
      <img src="images/star-fill.svg" alt="star rating graphic">
      <img src="images/star-fill.svg" alt="star rating graphic">
      <img src="images/star-fill.svg" alt="star rating graphic">
      <img src="images/star-fill.svg" alt="star rating graphic">
    </div>
    <p>${a.text}</p>
    `,t=document.createElement("div");return t.classList.add("testimonials-card-container"),t.innerHTML=e,t};a.forEach((a,i)=>{let s=t(a);0===i&&s.classList.add("active--testimonial"),e.appendChild(s)});let i=Array.from(e.children),s=document.querySelectorAll(".dot-tabs"),r=document.querySelector(".prev-arrow"),c=document.querySelector(".next-arrow"),l=0;s[0].classList.add("active--tab"),r.classList.add("deactivated--arrow"),s.forEach((a,e)=>{a.addEventListener("click",()=>{s.forEach(a=>{a.classList.contains("active--tab")&&a.classList.remove("active--tab")}),a.classList.add("active--tab"),0!=e?r.classList.remove("deactivated--arrow"):r.classList.add("deactivated--arrow"),e==s.length-1?c.classList.add("deactivated--arrow"):c.classList.remove("deactivated--arrow"),i.forEach(a=>{a.classList.contains("active--testimonial")&&a.classList.remove("active--testimonial")}),i[e].classList.add("active--testimonial"),l=e})}),r.addEventListener("click",()=>{0!=l&&(i.forEach(a=>{a.classList.contains("active--testimonial")&&a.classList.remove("active--testimonial")}),i[l-1].classList.add("active--testimonial"),0==(l-=1)&&(r.classList.add("deactivated--arrow"),c.classList.remove("deactivated--arrow")),s.forEach(a=>{a.classList.contains("active--tab")&&a.classList.remove("active--tab"),s[l].classList.add("active--tab")}))}),c.addEventListener("click",()=>{l!=i.length-1&&(i.forEach(a=>{a.classList.contains("active--testimonial")&&a.classList.remove("active--testimonial")}),i[l+1].classList.add("active--testimonial"),(l+=1)==i.length-1&&(c.classList.add("deactivated--arrow"),r.classList.remove("deactivated--arrow")),s.forEach(a=>{a.classList.contains("active--tab")&&a.classList.remove("active--tab"),s[l].classList.add("active--tab")}))})});